## NORMALIZATION PROBLEM


In [5]:
import numpy as np

In [7]:
X = np.random.random((5,5))

#Finding the standard devi of each values in the array X

f = np.std(X)

#Finding the mean of all the values inside the array

v = np.mean(X)

#Formula for Normalization, used on each value in the array

z = (X - v) / f

#Print the final values after the Normalization solution
print (z)

#save array Z using the file name X_normalized.npy and printing that its succesfully saved
np.save('X_normalized.npy', z)

print ("\nThe work has been saved at 'X_normalized.npy' ")

[[ 1.35610554  0.54548738 -1.6269168  -1.04006236  0.97047142]
 [ 0.28802828 -1.45995111  0.6781153  -0.45665537  1.1707619 ]
 [-1.28730078 -0.61422267  1.36216997  0.73941187  0.76619635]
 [-1.53160893  1.19324488 -1.26843595 -0.93790831  0.1260933 ]
 [ 0.9154529   0.3115185  -0.72881526  0.98398665 -0.45516669]]

The work has been saved at 'X_normalized.npy' 


## DIVISIBLE BY 3 PROBLEM

In [10]:
import numpy as np

#Making an Array with the values 1 to 100 inside the variable ndarray

ndarray = np.arange(1,101,1)

#Organizing the array by 10x10 in ascending order

c = ndarray.reshape(10, 10)

#Squaring all numbers in the array

d = np.square(c)

#Storing all elements that are divisible by 3 at variable e

e = d[d % 3 == 0]

#Printing the variable c which contains the values 1 to 100 in an 10x10 array

print (c)

#Space for asthethic

print ()

#Printing the variable e which contains all values divisible by 3

print (e)

#save array using the file name div_by_3.npy and printing that it is saved. 
np.save('div_by_3.npy', e)

print ("\nThe work has been saved at 'div_by_3.npy' ")

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]

The work has been saved at 'div_by_3.npy' 
