## NORMALIZATION PROBLEM


In [2]:
import numpy as np

In [3]:
#Making an 5x5 array with random values inside the variable X
X = np.random.random((5,5))

#Finding the standard devi of each values in the array X

f = np.std(X)

#Finding the mean of all the values inside the array

v = np.mean(X)

#Formula for Normalization, used on each value in the array

z = (X - v) / f

#Print the final values after the Normalization solution
print (z)

#save array Z using the file name X_normalized.npy and printing that its succesfully saved
np.save('X_normalized.npy', z)

print ("\nThe work has been saved at 'X_normalized.npy' ")

[[-1.47408233  1.22024519 -1.50087483  1.53789294 -0.27483147]
 [-0.82587668  0.08033121  0.14796742  0.76299681  1.06295479]
 [ 0.30265426 -0.46198657 -0.76811882 -1.0020956  -1.45703485]
 [ 1.10434712  0.29018808 -0.91200695  1.29626906  1.519171  ]
 [ 0.29262041 -1.59230065  0.70815112 -0.71832689  0.66174624]]

The work has been saved at 'X_normalized.npy' 


## DIVISIBLE BY 3 PROBLEM

In [5]:
import numpy as np

#Making an Array with the values 1 to 100 inside the variable ndarray

ndarray = np.arange(1,101,1)

#Organizing the array by 10x10 in ascending order

c = ndarray.reshape(10, 10)

#Squaring all numbers in the array

d = np.square(c)

#Storing all elements that are divisible by 3 at variable e

e = d[d % 3 == 0]

#Printing the variable c which contains the values 1 to 100 in an 10x10 array

print (c)

#Space for asthethic

print ()

#Printing the variable e which contains all values divisible by 3

print (e)

#save array using the file name div_by_3.npy and printing that it is saved. 
np.save('div_by_3.npy', e)

print ("\nThe work has been saved at 'div_by_3.npy' ")

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]

The work has been saved at 'div_by_3.npy' 
